apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chat-app
spec:
  selector:
    app: backend  # Make sure the backend deployment's labels match this
  ports:
    - protocol: TCP
      port: 5001  # Default MongoDB port
      targetPort: 5001  # Or the port your backend is listening on
