apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: chat-app
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017  # MongoDB's default port
      targetPort: 27017
